name = "王思兵"
description = "Herring Cove is ported from the jekyll theme of the same name"
license = "MIT"
tags = ["blog", "company"]
min_version = 0.20

[author]
    name = "spf13"
    homepage = "https://wsibing.github.io/"

# If Porting existing theme
[original]
    author =  "arnp"
    repo = "https://wsibing.github.io/"
